import { baseLayout } from './base.layout';
import { tw } from './tailwind.styles';
import {
  AdminDailyReportVars,
  RenderedEmail,
} from '@modules/mail/interfaces/template.interfaces';

/**
 * Render admin daily report template
 */
export const renderAdminDailyReportTemplate = (
  variables: AdminDailyReportVars,
): RenderedEmail => {
  const rows = variables.topArticles
    .map(
      (article) => `
    <tr>
      <td style="${tw.td} ${tw.tdCenter}">#${article.rank}</td>
      <td style="${tw.td}">${article.title}</td>
      <td style="${tw.td} ${tw.tdRight}">${article.allTimeLikes.toLocaleString()}</td>
      <td style="${tw.td} ${tw.tdRight} color: #16a34a; font-weight: 600;">+${article.likesGained}</td>
    </tr>
  `,
    )
    .join('');

  const html = baseLayout({
    title: 'Daily Admin Report',
    headerEmoji: '📊',
    headerTitle: 'Daily Activity Report',
    previewText: `Summary for ${variables.date}: +${variables.totalLikesGained.toLocaleString()} total likes gained.`,
    contentHtml: `
      <p style="${tw.p}">Here is the platform activity summary for <strong style="${tw.strong}">${variables.date}</strong>.</p>
      
      <div style="${tw.statsContainer}">
        <p style="${tw.statsValue}">+${variables.totalLikesGained.toLocaleString()}</p>
        <p style="${tw.statsLabel}">Total Likes Gained Yesterday</p>
      </div>

      <h2 style="${tw.h2}">Top 5 Articles</h2>
      <table style="${tw.table}">
        <thead>
          <tr>
            <th style="${tw.th} width: 60px; text-align: center;">Rank</th>
            <th style="${tw.th}">Article Title</th>
            <th style="${tw.th} text-align: right;">Total</th>
            <th style="${tw.th} text-align: right;">Growth</th>
          </tr>
        </thead>
        <tbody>
          ${rows.length > 0 ? rows : '<tr><td colspan="4" style="padding: 32px; text-align: center; color: #94a3b8;">No data available for top articles.</td></tr>'}
        </tbody>
      </table>
      
      <div style="${tw.divider}"></div>
      <p style="${tw.footerText}">
        This is an automated report generated by the Blog Platform Reporting System.
      </p>
    `,
  });

  const text = `
Daily Activity Report: ${variables.date}

Total Likes Gained Yesterday: +${variables.totalLikesGained.toLocaleString()}

Top 5 Articles:
${variables.topArticles
  .map(
    (article) =>
      `#${article.rank} - ${article.title} | Total: ${article.allTimeLikes.toLocaleString()} | Growth: +${article.likesGained}`,
  )
  .join('\n')}

Generated automatically by Blog Platform Reporting System.
  `.trim();

  return { html, text };
};
